import { Channel } from "../types/tv";

export const DEFAULT_CHANNELS: Channel[] = [
  {
    id: "ch-01",
    number: 1,
    name: "CCTV-1 综合频道",
    category: "live",
    streamUrl: "/live-stream/hls/1/index.m3u8",
    description: "中国中央电视台综合频道 · 此时此刻实时直播",
  },
  {
    id: "ch-02",
    number: 2,
    name: "CCTV-2 财经频道",
    category: "live",
    streamUrl: "/live-stream/hls/2/index.m3u8",
    description: "经济信息与全球财经热点实时追踪",
  },
  {
    id: "ch-03",
    number: 3,
    name: "CCTV-3 综艺频道",
    category: "live",
    streamUrl: "/live-stream/hls/3/index.m3u8",
    description: "国家级大型文艺演出与经典综艺",
  },
  {
    id: "ch-04",
    number: 4,
    name: "CCTV-4 中文国际",
    category: "live",
    streamUrl: "/live-stream/hls/4/index.m3u8",
    description: "面向全球华人的中国与世界新闻",
  },
  {
    id: "ch-05",
    number: 5,
    name: "CCTV-5 体育频道",
    category: "live",
    streamUrl: "/live-stream/hls/5/index.m3u8",
    description: "顶级国内外重大体育赛事现场直播",
  },
  {
    id: "ch-06",
    number: 6,
    name: "CCTV-6 电影频道",
    category: "live",
    streamUrl: "/live-stream/hls/6/index.m3u8",
    description: "中外优秀故事片与胶片展映",
  },
  {
    id: "ch-07",
    number: 7,
    name: "CCTV-7 国防军事",
    category: "live",
    streamUrl: "/live-stream/hls/7/index.m3u8",
    description: "军事资讯与强军纪实报道",
  },
  {
    id: "ch-08",
    number: 8,
    name: "CCTV-8 电视剧频道",
    category: "live",
    streamUrl: "/live-stream/hls/8/index.m3u8",
    description: "黄金档精品剧场连续播映",
  },
  {
    id: "ch-09",
    number: 9,
    name: "CCTV-9 纪录频道",
    category: "live",
    streamUrl: "/live-stream/hls/9/index.m3u8",
    description: "人文历史与自然地理高清纪录大片",
  },
  {
    id: "ch-10",
    number: 10,
    name: "CCTV-10 科教频道",
    category: "live",
    streamUrl: "/live-stream/hls/10/index.m3u8",
    description: "探索与发现 · 百家讲坛与科学纪实",
  },
  {
    id: "ch-11",
    number: 11,
    name: "CCTV-11 戏曲频道",
    category: "live",
    streamUrl: "/live-stream/hls/11/index.m3u8",
    description: "京剧与全国各地方戏曲经典荟萃",
  },
  {
    id: "ch-12",
    number: 12,
    name: "CCTV-12 社会与法",
    category: "live",
    streamUrl: "/live-stream/hls/12/index.m3u8",
    description: "今日说法与社会法律专题",
  },
  {
    id: "ch-13",
    number: 13,
    name: "CCTV-13 新闻频道",
    category: "live",
    streamUrl: "/live-stream/hls/13/index.m3u8",
    description: "24小时全天候滚动新闻与突发事件直击",
  },
  {
    id: "ch-14",
    number: 14,
    name: "CCTV-14 少儿频道",
    category: "live",
    streamUrl: "/live-stream/hls/14/index.m3u8",
    description: "大风车、智慧树与中外优秀动画片",
  },
  {
    id: "ch-15",
    number: 15,
    name: "CCTV-15 音乐频道",
    category: "live",
    streamUrl: "/live-stream/hls/15/index.m3u8",
    description: "音乐现场、金曲演唱会与交响乐",
  },
  {
    id: "ch-16",
    number: 16,
    name: "CCTV-16 奥林匹克",
    category: "live",
    streamUrl: "/live-stream/hls/16/index.m3u8",
    description: "奥林匹克赛事与奥林匹克精神专栏",
  },
  {
    id: "ch-17",
    number: 17,
    name: "CCTV-17 农业农村",
    category: "live",
    streamUrl: "/live-stream/hls/17/index.m3u8",
    description: "乡村振兴与三农天地最新纪实",
  },
  {
    id: "ch-18",
    number: 18,
    name: "湖南卫视",
    category: "live",
    streamUrl: "/live-stream/hls/18/index.m3u8",
    description: "湖南广播电视台卫星频道实时直播",
  },
  {
    id: "ch-19",
    number: 19,
    name: "浙江卫视",
    category: "live",
    streamUrl: "/live-stream/hls/19/index.m3u8",
    description: "浙江广播电视集团卫星频道实时直播",
  },
  {
    id: "ch-20",
    number: 20,
    name: "江苏卫视",
    category: "live",
    streamUrl: "/live-stream/hls/20/index.m3u8",
    description: "江苏省广播电视总台卫星频道实时直播",
  },
  {
    id: "ch-21",
    number: 21,
    name: "东方卫视",
    category: "live",
    streamUrl: "/live-stream/hls/21/index.m3u8",
    description: "上海广播电视台卫星频道实时直播",
  },
  {
    id: "ch-22",
    number: 22,
    name: "北京卫视",
    category: "live",
    streamUrl: "/live-stream/hls/22/index.m3u8",
    description: "北京广播电视台卫星频道实时直播",
  },
  {
    id: "ch-99",
    number: 99,
    name: "【彩蛋】周二检修测试卡",
    category: "test",
    streamUrl: "",
    isTestCard: true,
    description: "90/00 年代每周二下午各电视台停播检修 · PM5544 彩色圆盘与 1kHz 标准测试音",
  },
];
